---
##################################################################################################
# vue service
##################################################################################################
apiVersion: v1
kind: Service
metadata:
  name: vue
  labels:
    app: vue
    service: vue
spec:
  type: LoadBalancer
  ports:
  - port: 80
    name: http
    targetPort: 80
  selector:
    app: vue
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vue-v1
  labels:
    app: vue
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vue
      version: v1
  template:
    metadata:
      labels:
        app: vue
        version: v1
    spec:
      nodeSelector:
        cloud.google.com/compute-class: Scale-Out
        kubernetes.io/arch: arm64
      containers:
      - name: vue
        image: asia-east1-docker.pkg.dev/wood-378110/wodd/vue:v1
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            cpu: "250m"
            memory: "128Mi"
          limits:
            cpu: "250m"
            memory: "128Mi"
        ports:
        - containerPort: 8099
---