---
##################################################################################################
# rank service
##################################################################################################
apiVersion: v1
kind: Service
metadata:
  name: rank
  labels:
    app: rank
    service: rank
spec:
  ports:
  - port: 9081
    name: http
  selector:
    app: rank
---
# apiVersion: v1
# kind: ServiceAccount
# metadata:
#   name: bookinfo-rank
#   labels:
#     account: rank
# ---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rank-v1
  labels:
    app: rank
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rank
      version: v1
  template:
    metadata:
      labels:
        app: rank
        version: v1
    spec:
      # serviceAccountName: bookinfo-rank
      # nodeSelector:
      #   cloud.google.com/compute-class: Scale-Out
      #   kubernetes.io/arch: arm64
      containers:
      - name: rank
        image: us-central1-docker.pkg.dev/wood-378110/wood/rank-amd64:v1
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            cpu: "250m"
            memory: "128Mi"
          limits:
            cpu: "250m"
            memory: "128Mi"
        ports:
        - containerPort: 9081
---